# Generated by Django 5.2.4 on 2025-07-06 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_rename_compagny_company"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Company",
        ),
    ]
