# Generated by Django 5.2.4 on 2025-12-11 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_rename_email_verified_user_is_verified_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="verification_code",
            new_name="email_verification_code",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="verification_code_expires",
            new_name="email_verification_code_expires",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="is_verified",
            new_name="email_verified",
        ),
    ]
