# Generated by Django 5.2.4 on 2026-03-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0010_user_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_reset_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="password_reset_code_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
