# Generated by Django 5.2.4 on 2026-05-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="accept_cgu",
            field=models.BooleanField(default=False),
        ),
    ]
