# Generated by Django 5.2.4 on 2026-09-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity_verification", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identityverificationrequest",
            name="id_card_front",
            field=models.ImageField(upload_to="verifications/%Y%m%d/"),
        ),
        migrations.AlterField(
            model_name="identityverificationrequest",
            name="selfie_with_id",
            field=models.ImageField(upload_to="verifications/%Y%m%d/"),
        ),
    ]
