services:
  database:
    image:
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 
      MYSQL_USER: 
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: 
    volumes:
      - mysql-db:/var/lib/mysql

volume:
  mysql-db: