# Generated by Django 5.2.4 on 2025-07-06 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_compagny"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Compagny",
            new_name="Company",
        ),
    ]
