# Generated by Django 5.2.4 on 2025-12-11 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_user_email_verification_code_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="email_verified",
            new_name="is_verified",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="email_verification_code",
            new_name="verification_code",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="email_verification_code_expires",
            new_name="verification_code_expires",
        ),
    ]
