# Generated by Django 5.2.4 on 2026-03-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0009_user_failed_login_attempts_user_last_failed_login_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
