# Generated by Django 5.2.4 on 2026-05-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0013_user_accept_cgu"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="identity_verified",
            field=models.BooleanField(default=False),
        ),
    ]
