# Generated by Django 5.2.4 on 2026-05-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0014_user_identity_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="identity_requested",
            field=models.BooleanField(default=False),
        ),
    ]
