# Generated by Django 5.2.4 on 2026-05-08 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0015_user_identity_requested"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
    ]
