# Generated by Django 5.2.4 on 2026-05-09 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0016_remove_user_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="bio",
        ),
    ]
