# Generated by Django 5.2.4 on 2026-06-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0017_remove_user_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="account_deactivated_by_user",
            field=models.BooleanField(default=False),
        ),
    ]
