# Generated by Django 5.2.4 on 2026-05-06 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IdentityVerificationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_card_front",
                    models.ImageField(upload_to="verifications/id_cards/%Y/%m/%d/"),
                ),
                (
                    "selfie_with_id",
                    models.ImageField(upload_to="verifications/selfies/%Y/%m/%d/"),
                ),
                (
                    "ai_score",
                    models.FloatField(
                        blank=True, help_text="Score de confiance IA (0-1)", null=True
                    ),
                ),
                (
                    "ai_details",
                    models.JSONField(
                        blank=True,
                        help_text="Détails bruts de l'analyse IA/API",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente de revue"),
                            ("APPROVED", "Validé (Identité confirmée)"),
                            ("REJECTED", "Rejeté"),
                            ("ERROR", "Erreur de traitement"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, help_text="Raison du rejet (visible par l'admin)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_staff": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity_request",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
