# Generated by Django 5.2.4 on 2025-12-10 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="publication",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="publication.publication",
            ),
        ),
    ]
