# Generated by Django 5.2.4 on 2026-05-14 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publication", "0002_alter_comment_publication"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicationLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PublicationMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="publications/")),
                (
                    "media_type",
                    models.CharField(
                        choices=[("IMAGE", "Image"), ("VIDEO", "Video")], max_length=10
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="publication",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="comment",
            name="likes",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="description",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="likes",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="media",
        ),
        migrations.AddField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="caption",
            field=models.TextField(blank=True, max_length=2200),
        ),
        migrations.AddField(
            model_name="publication",
            name="comments_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="publication",
            name="is_edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="publication",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="description",
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="publication",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="publication",
            index=models.Index(
                fields=["created_at"], name="publication_created_0c485e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publication",
            index=models.Index(
                fields=["author", "-created_at"], name="publication_author__48d9f3_idx"
            ),
        ),
        migrations.AddField(
            model_name="publicationlike",
            name="publication",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="publication.publication",
            ),
        ),
        migrations.AddField(
            model_name="publicationlike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publication_likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="publicationmedia",
            name="publication",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medias",
                to="publication.publication",
            ),
        ),
        migrations.AddIndex(
            model_name="publicationlike",
            index=models.Index(
                fields=["publication"], name="publication_publica_0d6e96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publicationlike",
            index=models.Index(fields=["user"], name="publication_user_id_0f0358_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="publicationlike",
            unique_together={("user", "publication")},
        ),
    ]
