# Generated by Django 5.2.4 on 2026-09-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publication", "0003_publicationlike_publicationmedia_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="publication",
            name="caption",
            field=models.TextField(max_length=2200),
        ),
        migrations.DeleteModel(
            name="PublicationMedia",
        ),
    ]
