# Generated by Django 5.2.4 on 2025-07-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="description",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
    ]
