USER_NOT_FOUND="No active account was found using the credentials provided."
ACCOUNT_BLOCKED="Your account has been temporarily locked for security reasons. Please try again in {minutes_remaining} minutes."
ACCOUNT_BAN="Your account has been deactivated by the administration. Please contact support."
ACCOUNT_LOCKED="Too many failed attempts. Account locked for 10 minutes."
PASSWORD_FAILED="Incorrect username or password: {e}"